# Generated by Django 4.2.8 on 2023-12-06 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cajero', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventas',
            old_name='cantidad',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='producto',
        ),
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cajero.ventas')),
            ],
        ),
    ]
